name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64

      - name: Build Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release -j

      - name: Prepare artifact files
        run: |
          mkdir -p ./artifact/
          cp ./build/Release/csf.dll ./artifact
          cp ./tools/for-linux ./artifact/bedrock_server
          chmod 777 ./artifact/bedrock_server
          chmod +x ./artifact/bedrock_server
        shell: bash

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: "./csf_for_linux.zip"
          directory: "./artifact/"
          path: "./bedrock_server"
          type: "zip"

      - name: Upload build files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: ./artifact

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: "Release"
          tag_name: "v2"
          token: ${{ secrets.GLOBAL_TOKEN }}
          files: |
            ./artifact/csf.dll
            ./artifact/csf_for_linux.zip